version: '3.7'

services:
  web:
    build: .
    command: python /server/manage.py runserver 0.0.0.0:8000
    container_name: project-tracker-server
    ports:
      - "8000:8000"
    volumes:
      - .:/server

# To Expose, use reverse proxy and network
